version: '3.8'

services:
  shared-micro-front-end-app:
    build:
      context: ./shared-micro-front-end-app
    container_name: shared-micro-front-end-app
    ports:
      - "8083:80" # Map port 8083 to the app's NGINX port

  usermanagement:
    build:
      context: ./userManagement
    container_name: user-management
    ports:
      - "8087:80" # Map port 8087 to the app's NGINX port

  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard
    ports:
      - "8089:80" # Map port 8089 to the app's NGINX port

  footer:
    build:
      context: ./footer
    container_name: footer
    ports:
      - "8081:80" # Map port 8081 to the app's NGINX port

  header:
    build:
      context: ./header
    container_name: header
    ports:
      - "8082:80" # Map port 8082 to the app's NGINX port

  host:
    build:
      context: ./host
    container_name: host
    ports:
      - "8085:80" # Map port 8085 to the app's NGINX port

  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: mfe-reverse-proxy
    ports:
      - "80:80" # Expose the reverse proxy on port 80
    depends_on:
      - shared-micro-front-end-app
      - usermanagement
      - dashboard
      - footer
      - header
      - host
